### ISSUE TITLE
Little things on latest RDF push

### ISSUE THREAD

**Issue by legel** [scrapinghub/extruct#28]
Testing out the new RDF push, just some quick things that came up with possible fixes:
- `pip install extruct[rdfa]` didn't get the latest RDF files, had to clone from git (assuming this is by design but mentioning just in case)
- The example in the README led to this error `rdflib.plugin.PluginException: No plugin registered for (json-ld, <class 'rdflib.serializer.Serializer'>)`.  I'm not sure if this is because of how I downloaded RDFlib previously, but in any case the fix for me was the following: `git clone https://github.com/RDFLib/rdflib-jsonld.git && cd rdflib-jsonld && python setup.py install`
- (small typo) README file has `url='http://www.exaple.com/index.html'` -> `example.com`

I'd like to put this in a pull request but not sure how best to handle the middle case in particular.

**Comment by redapple** [comment]
Hi @legel , thanks for you feedback.

1) the "rdfa" extra adds rdflib/rdflib and rdflib/rdflib-jsonld dependencies, but the actual RDFa parser is based on pyRDFa3 code with some patches, which is copied into the codebase. I'll have a go at using a git submodule from a fork of mine, or try to get the patches merged upstream (rdflib or pyrdfa3).
2) indeed, that could be related to how you installed rdflib. when rdflib-jsonld gets installed, [their setup.py registers the json-ld plugin](https://github.com/RDFLib/rdflib-jsonld/blob/3563caf75295d9ee382b54fb2f812c6c3edffee3/setup.py#L97) for parsing and serializing 
3) I fixed the URL in the README. Nice catch!

**Comment by redapple** [comment]
Hey @legel , I just released extruct 0.3.0a1 which used rdflib directly without copying pyRdfa3.
Would this release fix the issues you have?

**Comment by redapple** [comment]
@legel , did you get to test 0.3.0a1 by any chance?

**Comment by legel** [comment]
@redapple I tested again on a fresh EC2 Ubuntu 16.04 instance, and unfortunately this is not yet resolved.

Not able to get RDFa through pip:
![Not able to get RDFa through pip](https://ibin.co/38ziYHwhtzdB.png) 

Not able to get RDFlib through git:
![Not able to get RDFlib through git](https://ibin.co/38zjCsQJC4wz.png)

Once I manually cloned and installed the RDFlib installation into my dist-packages, then it worked:
![Success after manual install](https://ibin.co/38zjuaTZVfHF.png)

**Comment by redapple** [comment]
hi @legel , 
pip by default will not install 0.3.0a1 because it's alpha level.
To install it, you need to do
`pip install --upgrade extruct[rdfa]==0.3.0a1` (explicit version install)
or 
``pip install --upgrade --pre extruct[rdfa]` (to [allow pre-releases](https://pip.pypa.io/en/stable/reference/pip_install/#pre-release-versions))
can you try that?

**Comment by redapple** [comment]
hi @legel , I've released extruct 0.3.1 with rdfa support by default.
Please check it out. Cheers.

**Comment by andrin-n-dream** [comment]
I had to add the following to my python script in order to make it work
```python
from rdflib.plugin import register, Serializer, Parser
register('json-ld', Serializer, 'rdflib_jsonld.serializer', 'JsonLDSerializer')
register('json-ld', Parser, 'rdflib_jsonld.parser', 'JsonLDParser')
```
